### PR TITLE
KTL-1248: Update hero screen

### PR DESCRIPTION
**Pull request by krutilov**

### CODE REVIEW

**Review by nikpachoo — CHANGES_REQUESTED** [review]
Screenshot 2023-12-21 at 12 16 11
Please, check 1280px width, there is a margin.

**Comment by nikpachoo** [comment]
Screenshot 2023-12-21 at 12 19 04
Also, check the margin.

**Comment by nikpachoo** [comment]
Screenshot 2023-12-21 at 12 24 55
Check 1000px and 744px, the margin should be 72px. Now it is 96px.

**Comment by krutilov** [comment]
Fixed, also fixed a bug with mobile landscape from KTL-1116

**Review by nikpachoo — APPROVED** [review]

**Pull request merged**
