### PR TITLE
KT-16141: Spread markers around the city location 

### PR DESCRIPTION
**Pull request by voddan**
I took the liberty to add a small modification to the code of the site so that problems described at KT-16141 would be (partially) resolved.

Please check the code carefully since it was my first time writing JS. I did my best to emulate the code style of the project.

### CODE REVIEW

**Comment by voddan** [comment]
I was able to run the site when I replaced "0.0.0.0" with "localhost" in `kotlin-website.py`. That's where the second commit is coming from.

**Comment by kisenka** [comment]
@voddan thanks! In some cases dots placed on the water :)

image

@belovrv If it's ok I'll accept this PR.

**Comment by kisenka** [comment]
@voddan ping

**Comment by voddan** [comment]
@kisenka Yes? I thought this PR was dead since it has never been merged for some reason.

**Comment by kisenka** [comment]
My question was "In some cases dots placed on the water. If it's ok I'll accept this PR."

**Comment by voddan** [comment]
@kisenka Oh, I didn't get that it was a question. 

Dots on water are ok since there is really no other solution - I mean, if I place dots only on land someone might think that those are all JetBrains offices 0_o.

Sorry I didn't react to your previous comment properly - I was sure you were in the process of merging it or rejected the PR for some internal reason. 

Frankly I would prefer a real solution with a drop-down list than this hack, but it is still better than no solution at all

**Comment by kisenka** [comment]
@voddan no problem. I'm check your additions again and merge them.

**Comment by belovrv** [comment]
I don't think its a good solution for the problem. @kisenka, let's make a dot with a number of events and clicking on it will show all of them in the left menu.

**Pull request closed without merging**
