### PR TITLE
Version update for  coroutines-basic-jvm.md

### PR DESCRIPTION
**Pull request by rifatdover**
Version is 1.1.1 currently

### CODE REVIEW

**Comment by rifatdover** [comment]
I think it is not currently on maven. Only on bintray? I can not use it?

**Comment by rifatdover** [comment]
Can not resolve 1.1.1 but it is on version?
https://bintray.com/kotlin/kotlinx/kotlinx.coroutines/1.1.1

**Comment by rifatdover** [comment]
It is only on bintray not maven central. You can close it or merge it when ready.

**Comment by p7nov** [comment]
Thanks. We'll update this to the most recent version `1.3.2`.

**Pull request closed without merging**
