### PR TITLE
Update classes.md

### PR DESCRIPTION
**Pull request by dusanhornik**

### CODE REVIEW

**Comment by p7nov** [comment]
Thanks for your PR.
`var` is not a typo here. It shows that `age` can change in the future.

**Comment by dusanhornik** [comment]
In that case, you want to change the `val` into `var` in the next paragraph as they both suppose to represent the same class with only formatting differences.

**Comment by p7nov** [comment]
Yes, you're right, thank you. I'll reopen the PR, please commit that change if you want.

**Comment by dusanhornik** [comment]
done

**Pull request merged**
