### PR TITLE
Update idioms.md

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
I think it would be be better to write the variable in the braces, while using its value.
This would be easier to understand for everyone new to the language.

### CODE REVIEW

**Comment by yole** [comment]
Thanks for your contribution, but this really isn't idiomatic Kotlin code. The idiomatic way to write Kotlin is to avoid using redundant elements in the source code, and curly braces are redundant in this context.

**Comment by DipanshKhandelwal** [comment]
OK, i got it but then at some places it is used with braces while at others it is not.
Even when it contains a single word variable.

**Comment by yole** [comment]
The correct thing to do is to remove braces in those places where they are used with a single variable.

**Comment by DipanshKhandelwal** [comment]
Yes, i got it. Thanks.

**Pull request closed without merging**
