### PR TITLE
KT-47068: Backfill user groups positions and make position mandatory

### PR DESCRIPTION
**Pull request by krzema12**
Issue: https://youtrack.jetbrains.com/issue/KT-47068

This is a prerequisite prior to adding a map that visualizes them.

The positions were obtained by:
1. Putting all KUGs on a Google map (https://www.google.com/maps/d/u/0/edit?mid=1fz4Bs85kWUjHUBkZFXICXGNyP4Q5DtI4&usp=sharing). Google's geocoding algorithm was used, by
   simply searching for a given city and using the placemark suggested
   by Google. Sometimes, minor adjustments were needed that required
   logical thinking - I hope I got it correct, it can be always fixed
   iteratively.
2. Using such Kotlin script to modify `user-groups.yml`:

```kotlin
import com.charleskorn.kaml.Yaml
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import org.w3c.dom.Document
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory

@Serializable
data class Section(
    val section: String,
    val anchorId: String,
    val groups: List<Group>,
)

@Serializable
data class Group(
    val name: String,
    val country: String,
    val url: String,
    val position: Position? = null,
)

@Serializable
data class Position(
    val lat: Double,
    val lng: Double,
)

fun main() {

    val googleMapXml = File("/home/piotr/Downloads/KUG positions backfill.kml")
    val factory = DocumentBuilderFactory.newInstance()
    val builder = factory.newDocumentBuilder()
    val document: Document = builder.parse(googleMapXml)

    val placemarks = document.documentElement.getElementsByTagName("Placemark")
    val namesToPositions = (0 until placemarks.length).map { placemarkId ->
        val name = placemarks.item(placemarkId).childNodes.item(1).textContent
        val positionAsText = placemarks.item(placemarkId).childNodes.item(5).textContent.trim()
        val (longitude, latitude) = positionAsText.split(",")
        Group(
            name = name,
            country = "",
            url = "",
            position = Position(
                lat = latitude.toDouble(),
                lng = longitude.toDouble(),
            )
        )
    }.associateBy({ it.name }, { it.position })

    val userGroupsFile = File("/home/piotr/repos/kotlin-web-site/data/user-groups.yml")
    val userGroupsYml = userGroupsFile.readText()
    val yaml = Yaml(
        configuration = Yaml.default.configuration.copy(
            encodeDefaults = false,
        )
    )
    val sections = yaml.decodeFromString<List<Section>>(userGroupsYml)

    val modifiedSections = sections
        .map { section ->
            section.copy(
                groups = section.groups.map { group ->
                    val position = namesToPositions[group.name]
                        ?: throw IllegalArgumentException("Unknown position for '${group.name}'")
                    group.copy(position = position)
                }
            )
        }

    val modifiedUserGroupsYml = yaml.encodeToString(modifiedSections)
    userGroupsFile.writeText(
        modifiedUserGroupsYml
            // The YML library produces indentation in a different format than is used in user-groups.yml.
            // Below are some workarounds to make it unified.
            .replace("\"", "")
            .replace("\\", "\"")
            .replace("    ", "      ")
            .replace("  - ", "    - ")
    )
}
```

The script ensures that each user group gets a position (throws an
exception otherwise).

### CODE REVIEW

**Review by nikpachoo — APPROVED** [review]
@krzema12 great job, thank you!

**Review by nikpachoo — CHANGES_REQUESTED** [review]
@krzema12
I apologize for the inconsistency. I missed something important.

We already have a couple of scripts that obtain coordinates for [universities](https://github.com/JetBrains/kotlin-web-site/blob/master/scripts/universities_geolocator.py) and [events](https://github.com/JetBrains/kotlin-web-site/blob/master/scripts/events_geolocator.py).

I would like to suggest to:
1) Make script based on [universities_geolocator.py](https://github.com/JetBrains/kotlin-web-site/blob/master/scripts/universities_geolocator.py), and add it into "script" folder. 
2) Update KUG coordinates with the script. 
3) Provide a little instruction in README.md, how to update KUG.

**Comment by krzema12** [comment]
@nikpachoo ok, I'll add such script. Are you OK with leaving the existing locations as is? I did my best to make the quality of this data high, and going through over 200 points again is something I'd like to avoid :sweat_smile: I see that the Python script uses Google geocoding anyway.

**Comment by nikpachoo** [comment]
@krzema12, 
Yes! definitely we can leave locations made by you, everything is fine.

**Comment by krzema12** [comment]
@nikpachoo 
I'm trying to use the `universities_geolocator.py` but getting `<[REQUEST_DENIED] Google - Geocode [empty]>` when the script actually makes a request to Google. I think Google's geocoding API is paid and I need to provide an API key which I don't have. There's also a possibility I misuse the script. Could you teach me how to use it?

CC @zoobestik since I see that you recently made the switch to Google geolocation: https://github.com/JetBrains/kotlin-web-site/commit/294c7b507b6acf8a1f3a7cee1ab8040738ca2970

**Comment by zoobestik** [comment]
Hi, @krzema12, thanks for your contributions ❤️

We are moving from Yandex (it was for free) to Google, cause it's not good enough to translate coordinates from Yandex Geocoding API to Google Map API.

Usage smth like this:
```bash
$ GOOGLE_API_KEY="..." python scripts/universities_geolocator.py
``` 
I'll add it to README.

And you are right, it's required google api key. You can [generate](https://console.cloud.google.com/google/maps-apis/credentials) it after enabling HTTP geolocation in [Google Cloud Console](https://console.cloud.google.com/marketplace/product/google/geolocation.googleapis.com). it's looks like paid, but google provide 200$ for free usage any map api. Is it not enough to working with script?

**Comment by krzema12** [comment]
Thanks @zoobestik, I was able to generate the API key, but I'm still getting `REQUEST_DENIED` when passing it via `GOOGLE_API_KEY` env var. I also tried passing it like this, without success:

```
response = geocoder.google(location, key='...some secret api key...')
```

Here's my partially tested script for updating user groups - it would be cool if you could help me fully test it with Google API, then I can commit it. I tested it by simply removing `position` of some existing user group:

```
from os import path

import geocoder
from ruamel import yaml

data_folder = path.join(path.dirname(__file__), "../data")
data_file = path.join(data_folder, "user-groups.yml")

with open(data_file, encoding="utf-8") as points_file:
    sections = yaml.load(points_file, yaml.RoundTripLoader)

for n, section in enumerate(sections):
    for n, user_group in enumerate(section['groups']):
        city = user_group.get("name").replace("Kotlin", "").replace("User", "").replace("Group", "").strip()
        location = city + ", " + user_group.get("country")

        if 'position' in user_group:
            print(location + " (saved previous)")
            continue

        print("Process %s..." % location)

        response = geocoder.google(location)
        print(response)
        coordinates = response.latlng

        if coordinates is None or len(coordinates) == 0:
            raise Exception("Location not found: " + location)

        if response.ok is not True:
            raise Exception("Location not resolved: ", location)

        new_geo = {
            "lat": coordinates[0],
            "lng": coordinates[1],
        }

        print("Will coordinates for \"%s\":\nhttps://www.google.com/maps/search/?api=1&query=%s,%s""" % (
            location, new_geo['lat'], new_geo['lng']
        ))

        user_group['position'] = new_geo

with open(data_file, 'w') as points_file:
    yaml.dump(user_groups, stream=points_file, Dumper=yaml.RoundTripDumper, allow_unicode=True)
```

**Comment by zoobestik** [comment]
@krzema12, i think you  have a response like that:
```json
{
    "error_message" : "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
    "results" : [],
    "status" : "REQUEST_DENIED"
}
```

It's once requirement from google to have billing data for overusing payments. Without it keys don't work.

**Comment by krzema12** [comment]
@zoobestik I enabled billing and it still doesn't work. Under `response.error_message` I have `None`, whatever do.

I think it's not that crucial to make it work on my account - it's a one-time contribution from my side. It's more important to get it working for the people maintaining the locations of universities, user groups and so on :) Does the script work on your machine and with your API key?

**Comment by krzema12** [comment]
@nikpachoo @zoobestik I added a commit with the script; I tested by mocking Google's API:

```python
# response = geocoder.google(location)

class Response:
  def __init__(self, ok, latlng):
    self.ok = ok
    self.latlng = latlng

response = Response(True, (12.34, 56.78))
```

Hopefully it will work end-to-end :grinning:

**Comment by zoobestik** [comment]
@krzema12 yep, it works for me too. Pls, rebase it from master.

@nikpachoo PR looks good for me, lets look too.

**Review by nikpachoo — APPROVED** [review]

**Pull request merged**
