### PR TITLE
Updated description for constructor generation

### PR DESCRIPTION
**Pull request by derkork**
see: https://youtrack.jetbrains.com/issue/KT-6257

### CODE REVIEW

**Comment by derkork** [comment]
Ping?

**Comment by abreslav** [comment]
Sorry for the delay, reviewing now

**Comment by abreslav** [comment]
Ok, I'll fix the text and push the results. Thanks for bringing this up

**Comment by abreslav** [comment]
Done. Thanks again

**Comment by derkork** [comment]
Cool, thanks for clarifying the first sentence.

**Pull request closed without merging**
