### PR TITLE
Added the official Android documentation reference

### PR DESCRIPTION
**Pull request by dayanruben**

### CODE REVIEW

**Comment by yole** [comment]
How exactly does the linked page help developers get started with Kotlin for Android?

**Comment by dayanruben** [comment]
It can help the Android developers to find the documentation related to the integration of Kotlin to Android Studio and the other tools, for example.

**Comment by yole** [comment]
I've added a link to https://developer.android.com/samples/index.html?language=kotlin instead; I think it provides more useful information than the page you're suggesting to link to.

**Comment by dayanruben** [comment]
Okay, thank you!

**Pull request closed without merging**
