### PR TITLE
Add proper terminology for PascalCase

### PR DESCRIPTION
**Pull request by rsheasby**

### CODE REVIEW

**Comment by yole** [comment]
Could you please edit the text so that it does not have two clauses in parentheses one after the other?

**Comment by rsheasby** [comment]
Done! I tend to think it reads better without the explanation of what PascalCase is so I removed it entirely. Most developers should already know what it is or be able to figure it out from the example.

**Comment by yole** [comment]
I'd leave the explanation in. The Kotlin documentation is accessed by many novice developers who are many years younger than Pascal, so the term would be unfamiliar to them.

**Comment by rsheasby** [comment]
Sure I'll rephrase and add it back. I'm sure they would be able to figure it out from the example but whichever you prefer.

**Comment by rsheasby** [comment]
Done.

**Comment by rsheasby** [comment]
Just wanted to follow up on this PR? Are there more changes that need to happen before it can be merged?

**Comment by p7nov** [comment]
Thanks for your suggestion. 
However, we decided to use the term `camel case` throughout the docs to avoid introducing terms that may be unfamiliar.

Regards, Pavel
Kotlin Technical Writer.

**Pull request closed without merging**
