### PR TITLE
update: Compiler options in Gradle

### PR DESCRIPTION
**Pull request by katia-energizer**
Updated the compiler options in Gradle:
* Marked noStdlib and noReflect as deprecated; updated the description.
* Minor updates to the Dependency on the standard library section.
* Combined all compiler options into a single table for Gradle and Maven.

### CODE REVIEW

**Review by p7nov — APPROVED** [review]

**Review by ausatiy — APPROVED** [review]

**Comment by DfM7** [comment]
Is this PR really stale despite have two approvals?

**Comment by DfM7** [comment]
@katia-energizer @p7nov @koshachy 
Ping.

**Comment by DfM7** [comment]
@katia-energizer @p7nov @ausatiy @koshachy 
Sorry for tagging, but I'm wondering whether this PR should have been closed without merging.

**Comment by p7nov** [comment]
@DfM7 hi!
This PR was an attempt to restructure the descriptions of compiler options available in the Gradle plugin. We reviewed it and found some certain downsides of such a structure. Now we're planning to revamp the whole **Gradle** page because it has grown really big. This PR won't fit into these plans.

**Comment by DfM7** [comment]
@p7nov 
Thank you for the explanation! 😊

**Pull request closed without merging**
