### PR TITLE
js-project-setup.md: typo, `in` -> `is`

### PR DESCRIPTION
**Pull request by aSemy**
Fix typo: 

> In this case, the configuration object presented ~in~ is the

### CODE REVIEW

**Comment by aSemy** [comment]
> This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.

🙅‍♀️

**Comment by aSemy** [comment]
> This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.

🙅‍♀️

**Comment by koshachy** [comment]
Hey @aSemy!
Thanks for your contribution to the documentation.
The only reason why we process this PR so long is because we are thinking about revamping the whole document.
Sorry for the delay and for the inconvenience.

**Review by koshachy — APPROVED** [review]

**Comment by koshachy** [comment]
Hey @aSemy,
Thank you for your patience and understanding.
I've updated your PR and added some new changes in the documentation. 

Thanks for contributing to the project!

**Pull request merged**
