### PR TITLE
Added table of Kotlin visibility modifiers

### PR DESCRIPTION
**Pull request by edgeone89**
Added table of Kotlin visibility modifiers like in java tutorials

### CODE REVIEW

**Comment by yole** [comment]
This table is somewhat misleading. Unlike Java, in Kotlin you can apply visibility modifiers to top-level declarations, and the table doesn't reflect that. Also, I'm not sure whether it really adds much value here.

**Comment by edgeone89** [comment]
top-level declarations can be added in the table; and the table adds clarity while preserving compactness-conciseness of info

**Comment by DipanshKhandelwal** [comment]
Even it doesn't even explains all of those attributes, like Kotlin also have a concept of open classes and variables.Check [this](https://kotlinlang.org/docs/reference/classes.html#inheritance) out.

**Comment by edgeone89** [comment]
@DipanshKhandelwal 
could you, please, give your variant?

**Comment by p7nov** [comment]
Closing this since it doesn't provide the complete picture of the visibility modifiers usage and isn't updated for a long time.

**Pull request closed without merging**
