### PR TITLE
chore: added hyphenate to cross-platform word and removed from multiplatform word

### PR DESCRIPTION
**Pull request by PetrakovichVictoria**

### CODE REVIEW

**Review by katia-energizer — APPROVED** [review]
LGTM. But since most changes are in community files, please show to @meilalina

**Comment by meilalina** [comment]
Hi! LGTM too. We can try and fix the names in the future, however, they're named by the community, so not sure if we should

**Comment by PetrakovichVictoria** [comment]
> Hi! LGTM too. We can try and fix the names in the future, however, they're named by the community, so not sure if we should

Hi! Didn't catch from your answer should I merge this PR to the master branch or not:) Do you mean we should wait with this PR?

**Comment by meilalina** [comment]
Sure, you can merge. I mean IMO it's not necessary to fix similar typos in the future :)

**Comment by PetrakovichVictoria** [comment]
> Sure, you can merge. I mean IMO it's not necessary to fix similar typos in the future :)

Okay, thank you:)

**Pull request merged**
