### PR TITLE
Fix small issues preventing local building and running

### PR DESCRIPTION
**Pull request by snowe2010**
This PR doesn't completely resolve the issues with generating the web site, but it does get past the issues preventing startup.

- Resolves issue with npm not installing in Docker
- Resolve issue with Flask using Werkzeug 3

### CODE REVIEW

**Review by nikpachoo — APPROVED** [review]

**Comment by nikpachoo** [comment]
@snowe2010, thank you!

**Review by nikpachoo — CHANGES_REQUESTED** [review]
It failed on the CI with an error. It seems that there's a dependency issue:
```
Could not find a version that satisfies the requirement Werkzeug==2.2.2 
```

**Comment by snowe2010** [comment]
@nikpachoo hm. without knowing what the CI is running I cannot duplicate. I'm following the instructions from https://youtrack.jetbrains.com/issue/KT-47049 and it works to startup at the least.

**Comment by snowe2010** [comment]
I would need more information from @nikpachoo in order to duplicate locally to fix the build errors.

**Comment by berezinant** [comment]
Hi, @snowe2010, thanks for the PR!
I wanted to let you know that we had added Werkzeug in the scope of [this PR](https://github.com/JetBrains/kotlin-web-site/pull/4020/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552)
So for now I'm going to close this PR. If you have any questions/suggestions, feel free to suggest and/or open another PR

**Pull request closed without merging**
