### PR TITLE
Add summary sentences for `let` and `run` functionality

### PR DESCRIPTION
**Pull request by Kaaveh**
When I was reading the section of Scope functions, [I started to summarize for me to memorize them](https://blog.kotlin-academy.com/kotlin-scope-functions-for-dummies-cb8c8970b8d9). There are good summary sentences about `with`, `apply`, and `also` in the doc. I added summary sentences for `let` and `run`. I hope it's good enough.

### CODE REVIEW

**Comment by Kaaveh** [comment]
Hey guys!
Any update for reviewing this PR?
@sarahhaggarty @koshachy

**Comment by Kaaveh** [comment]
Hey @sarahhaggarty 
Is there any problem that this PR won't be reviewed?

**Review by sarahhaggarty — CHANGES_REQUESTED** [review]
Hi @Kaaveh!
Sorry for taking so long to review your PR. It's been a busy time in our team onboarding new members and preparing for the next Kotlin release. I also wanted to take some time to discuss your suggestions with someone from our developer advocate team.

Firstly, kudos to you for writing an article about Kotlin scope functions. It's nice to see that they inspired you so much!

Regarding your suggested changes, after thinking long and hard about it I think we can add a slightly modified version of your summary sentence for non-extension `run`. For your suggestion for `let`, the trouble is that it is rather vague and we want summary sentences to have a clear intent. And for your `with` suggestion, the style doesn't really match our Kotlin style.

If you make the changes to your PR like I suggest, we can proceed with adding the new summary sentence for non-extension `run`.

Please don't be disheartened that not all your suggestions made it. We always appreciate new ideas being shared with us to make our docs better 😃

**Comment by Kaaveh** [comment]
Hey Sarah!
Thanks for your review. It's my honor to have contributed to my beloved programming language even very little, and also learn new things while contributing! I emitted the changes you required.
Out of curiosity, are there any documented guidelines for reading about contributing to Kotlin doc?

**Comment by sarahhaggarty** [comment]
Great! Could you combine all your commits into one commit as well?
Yes, we do! In our readme you can find in the [Contribution](https://github.com/JetBrains/kotlin-web-site#contribution) section a link to our [Kotlin documentation guidelines](https://docs.google.com/document/d/1mUuxK4xwzs3jtDGoJ5_zwYLaSEl13g_SuhODdFuh2Dc/edit#heading=h.hjojzyai18a6).

**Comment by Kaaveh** [comment]
Thanks @sarahhaggarty 
Done!

**Review by sarahhaggarty — APPROVED** [review]

**Comment by sarahhaggarty** [comment]
Thanks for your contribution @Kaaveh! 🚀

**Comment by Kaaveh** [comment]
I appreciate you taking the time to help me do this @sarahhaggarty .

**Pull request merged**
