### PR TITLE
Add idiom for constructors of generic classes in idioms.md

### PR DESCRIPTION
**Pull request by rocoty**
Added a new idiom for constructors of classes that require generic type information.

### CODE REVIEW

**Comment by yole** [comment]
Sorry, but I don't think that overriding `operator invoke()` in a companion object is an idiom that should be endorsed in the documentation. At the very least, the same trick can be accomplished with a top-level function that has the same name as the class, which requires much less magic.

**Comment by rocoty** [comment]
I see. That makes sense. Would it be possible to add your suggested variant to the idioms section then? I've found such generic factory functions to be very convenient.

**Comment by rocoty** [comment]
Alternatively, could it somehow be made into a language feature to have reified type parameters in constructors? I take it the biggest issue you had with my pull request was the "hacky" use of operator overloading, and so the idea itself isn't necessarily a bad one.

**Comment by yole** [comment]
Using a factory function with a reified type parameter and forwarding it to a class constructor is definitely a good idea. However, in my personal opinion, it's better to use factory functions that have descriptive names, not necessarily the same as the name of the class.

It might be possible to support inline constructors with reified type parameters, but that would be a major new language feature, best discussed elsewhere (for example, as a feature request in https://youtrack.jetbrains.com/issues/KT).

**Comment by rocoty** [comment]
Alright. Will do.

**Comment by rocoty** [comment]
Opened an issue on this here:
https://youtrack.jetbrains.com/issue/KT-13127

**Pull request closed without merging**
