### PR TITLE
Added Conditional single-expression functions

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
Added Conditional single-expression functions which returns true or false according to the condition checked.

### CODE REVIEW

**Comment by yole** [comment]
I'm not sure why a single-expression function that returns true or false is substantially different from a single-expression function that returns a value of any other type, and why it's worth highlighting as a separate idiom.

**Comment by DipanshKhandelwal** [comment]
I think its a bit different, because its not just returning a value but its computing before returning the value.

**Comment by yole** [comment]
Yes, almost all functions do that, in all languages. There is not anything specific to Kotlin in this.

**Comment by DipanshKhandelwal** [comment]
OK, thanks . I got it now , it's nothing to be written exclusively.

**Pull request closed without merging**
