### PR TITLE
Update delegation.md : parameter update in the class delegation example

### PR DESCRIPTION
**Pull request by yadavmangesh**
parameter update in the class delegation example

### CODE REVIEW

**Comment by yadavmangesh** [comment]
Hey @PetrakovichVictoria any update on the review status

**Comment by yadavmangesh** [comment]
hey @PetrakovichVictoria any update ?

**Comment by udalov** [comment]
I think these examples are fine as they are right now. You can delegate to an object whose static type is the interface type `Base`, it doesn't necessarily have to be some specific subtype such as `BaseImpl`. And it's important to demonstrate in the docs that it is possible, and actually used quite a lot in practice.

**Review by PetrakovichVictoria — COMMENTED** [review]
Hi @yadavmangesh, I discussed your PR with @udalov and he confirmed my doubts.

**Pull request closed without merging**
