### PR TITLE
Fix a minor typo in visibility modifiers reference documentation

### PR DESCRIPTION
**Pull request by KuSh**

### CODE REVIEW

**Comment by yole** [comment]
This is not a typo. The sentence means "find explanations of how the visibility modifiers apply to different types of declaring scopes".

**Comment by KuSh** [comment]
Ok thanks for the explanation. English isn't my mother tongue but I still find the phrasing a little bit awkward. I'm missing something after the word `these`, your explanation is easier to read!

**Comment by yole** [comment]
I've pushed a change rewording this sentence in a different way (similar to my comment).

**Comment by KuSh** [comment]
:+1:

**Pull request closed without merging**
