### PR TITLE
Update using-gradle.md

### PR DESCRIPTION
**Pull request by KotlinIsland**
- api/language remove "EXPERIMENTAL" from 1.4 and add 1.5
- jvm/jvmTarget add "14", default changed to "1.6"
- jvm/useIR added
- js/sourceMap default changed to `true`
- js/outputFile added default value

### CODE REVIEW

**Comment by p7nov** [comment]
Hi! 
Thank you for your PR, we've just merged similar updates in https://github.com/JetBrains/kotlin-web-site/pull/1840.

**Comment by KotlinIsland** [comment]
@p7nov some of those changes are incorrect
```kotlin
apiVersion = "1.2 (DEPRECATED)" // e: Unknown API version: 1.2 (DEPRECATED)
apiVersion = "1.5 (EXPERIMENTAL)" // e: Unknown API version: 1.5 (EXPERIMENTAL)
```
should be `"1.2" (DEPRECATED)` and `"1.5" (EXPERIMENTAL)`
And that PR doesn't contain default value for js/outputFile and sourceMap default
```
| `outputFile` | Destination *.js file for the compilation result |  | "\<buildDir>/js/packages/\<project.name>/kotlin/\<project.name>.js" |
| `sourceMap` | Generate source map |  | true |
```

Should I make a new PR with these changes?

**Comment by p7nov** [comment]
You're totally right. I'll reopen this request.
Sorry for closing it without a detailed review.

**Comment by KotlinIsland** [comment]
@p7nov Hmm, it looks kinda broken now
image
image

**Pull request merged**
