### PR TITLE
update: add more samples to kmm-samples.md

### PR DESCRIPTION
**Pull request by huynn109**

### CODE REVIEW

**Comment by huynn109** [comment]
Up to avoid stale.

**Comment by huynn109** [comment]
Up to avoid stale.

**Comment by koshachy** [comment]
Hey, @KaterinaPetrova, could you take a look?

**Comment by KaterinaPetrova** [comment]
Hi @huynn109! Sorry it took us so long to review. We really appreciate your contribution, but we've stopped accepting basic samples as the page now contains quite a lot of them. We now accept only samples that demonstrate some more rare features (for example, sharing between backend & client platforms). We will publish the criteria soon at the https://kotlinlang.org/docs/multiplatform-mobile-samples.html

**Pull request closed without merging**
